ns = "Idris2.Rust"
package= "Idris2Rust"
version= "0.0.1"

description = "Idris2 Rust backend"
link = "https://github.com/remimimimi/Idris2-Rust"
readme = "README.md"
modules = ["Idris2Rust.Main"]
depends = ["idris2", "base", "contrib", "network"]
license = "MIT"
main = "Idris2Rust.Main"
executable = "idris2rust"

[deps]

[dev-deps]
Base.IdrTest = "~0.0.1"
